import { SchoolData } from './types/studentTypes';

export const recentSearch = [
  { id: 1, title: 'Car Loan', category: 'Salary deduction', type: 'income' },
  { id: 2, title: 'Donations', category: 'Other income', type: 'income' },
  { id: 3, title: 'ICT Loan', category: 'interest on loan', type: 'expense' },
  { id: 4, title: 'Tuition', category: 'Fees', type: 'income' },
];

export const tabs = [
  { id: 1, title: 'Overview', badge: false },
  { id: 2, title: 'Income', badge: true },
  { id: 3, title: 'Expense', badge: true },
];

export const inventoryTabs = [
  { id: 1, title: 'All Products', badge: false },
  { id: 2, title: 'Available', badge: true },
  { id: 3, title: 'Low On Stock', badge: true },
  { id: 4, title: 'Out Of Stock', badge: true },
  { id: 5, title: 'Dispensed Products', badge: true },
];

export const payrollTabs = [
  { id: 1, title: 'Overview', badge: false },
  { id: 2, title: 'Allowance', badge: true },
  { id: 3, title: 'Deduction', badge: true },
];
export const ledgerTabs = [
  { id: 'income_ledger', title: 'Income Ledger', badge: false },
  { id: 'expense_ledger', title: 'Expense Ledger', badge: true },
  { id: 'asset_ledger', title: 'Asset Ledger', badge: true },
  { id: 'equity_ledger', title: 'Equity Ledger', badge: true },
  { id: 'liability_ledger', title: 'Liability Ledger', badge: true },
];

export const BalanceSheettabs = [
  // { id: 1, title: "Balance Sheet", badge: false },
  // { id: 2, title: "Profit and Loss Statement", badge: true },
  // { id: 3, title: "Cashflow Statement", badge: true },
  { id: 1, title: 'Balance Sheet', badge: false },
  { id: 2, title: 'Profit and Loss Statement', badge: true },
  { id: 4, title: 'Trial Balance', badge: true },
];

export const AssetandLiability = [
  // { id: 1, title: "Balance Sheet", badge: false },
  // { id: 2, title: "Profit and Loss Statement", badge: true },
  // { id: 3, title: "Cashflow Statement", badge: true },
  { id: 1, title: 'Overview', badge: false },
  { id: 2, title: 'Asset', badge: true },
  { id: 3, title: 'Liability', badge: true },
  { id: 4, title: 'Equity', badge: true },
];

export const BillsandFees = [
  { id: 1, title: 'All Fees', badge: false },
  { id: 2, title: 'Sent', badge: true },
  { id: 3, title: 'Unsent', badge: true },
  { id: 4, title: 'Draft', badge: true },
];

export const income = [
  { id: 1, amount: 'NGN 200,000', title: 'Books & Library Services' },
  { id: 2, amount: 'NGN 210,000', title: 'Donations' },
  { id: 3, amount: 'NGN 10,000', title: 'Fees' },
  { id: 4, amount: 'NGN 100,000', title: 'Other Income' },
  { id: 5, amount: 'NGN 500,000', title: 'Salary deduction' },
];

export const expense = [
  { id: 1, amount: 'NGN 200,000', title: 'Bad debt' },
  { id: 2, amount: 'NGN 210,000', title: 'Depreciation' },
  { id: 3, amount: 'NGN 10,000', title: 'Discarded Inventory' },
  { id: 4, amount: 'NGN 100,000', title: 'Discount' },
  { id: 5, amount: 'NGN 500,000', title: 'Other expense' },
];

export const tableData = [
  {
    id: 1,
    transaction_type: 'Tuition',
    transaction_group: 'fees',
    account: 'Income',
    amount: '200,000',
    approval_status: 'approved',
  },
  {
    id: 2,
    transaction_type: 'Car Loan',
    transaction_group: 'Salary Deduction',
    account: 'Income',
    amount: '500,000',
    approval_status: 'unapproved',
  },
];

export const sizeOptions: any = {
  clothings: [
    { id: 1, name: 'S' },
    { id: 2, name: 'M' },
    { id: 3, name: 'L' },
    { id: 4, name: 'XL' },
    { id: 5, name: 'XXL' },
  ],
  drug: [
    { id: 1, name: 'Bottle' },
    { id: 2, name: 'Carton' },
    { id: 3, name: 'Packet' },
    { id: 4, name: 'Pieces' },
  ],
  booksandstationaries: [
    { id: 1, name: '2B' },
    { id: 2, name: '20 leaves' },
    { id: 3, name: '40 leaves' },
    { id: 4, name: '60 leaves' },
    { id: 5, name: 'Carton' },
    { id: 6, name: 'Packet' },
    { id: 7, name: 'Pieces' },
  ],
  provisionsandtoiletries: [
    { id: 1, name: 'Bottle' },
    { id: 2, name: 'Carton' },
    { id: 3, name: 'Packet' },
    { id: 4, name: 'Pieces' },
    { id: 5, name: 'Refill' },
    { id: 6, name: 'Roll' },
    { id: 7, name: 'Sachet' },
    { id: 8, name: 'Tin' },
  ],
};

export const groupOptions: any = {
  clothings: [
    { id: 1, name: 'Footwear' },
    { id: 2, name: 'Other Clothing' },
    { id: 3, name: 'School Uniform' },
    { id: 4, name: 'Sportswear' },
    { id: 5, name: 'Sweater' },
  ],
  drug: [
    { id: 1, name: 'Anti-Bacterial' },
    { id: 2, name: 'Anti-Malaria' },
    { id: 3, name: 'Anti-Viral' },
    { id: 4, name: 'Painkillers' },
  ],
  booksandstationaries: [
    { id: 1, name: 'Notebooks' },
    { id: 2, name: 'Other Books and Stationaries' },
    { id: 3, name: 'Textbooks' },
    { id: 4, name: 'Writing Materials' },
  ],
  provisionsandtoiletries: [
    { id: 1, name: 'Beverage' },
    { id: 2, name: 'Biscuit' },
    { id: 3, name: 'Body Care' },
    { id: 4, name: 'Cereal' },
    { id: 5, name: 'House Cleaning' },
    { id: 6, name: 'Laundry' },
    { id: 7, name: 'Mouth Care' },
    { id: 8, name: 'Other Provisions & Toiletries' },
    { id: 9, name: 'Toilet Paper' },
  ],
};

export const studentData: SchoolData = {
  'Ambience Class': {
    students: [
      {
        idx: 7507,
        admissionnumber: 'A13',
        firstname: 'Israel',
        lastname: 'Chukwuka',
      },
    ],
    pagination_info: {
      total_students: 1,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Awesome Class': {
    students: [
      {
        idx: 7670,
        admissionnumber: '001',
        firstname: 'OLUWANIFEMI',
        lastname: 'OVIOSUN',
      },
      {
        idx: 7727,
        admissionnumber: '007A',
        firstname: 'Samuella',
        lastname: 'Olufemi',
      },
    ],
    pagination_info: {
      total_students: 2,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Basic 1': {
    students: [
      {
        idx: 7797,
        admissionnumber: 'PHY111',
        firstname: 'Femi',
        lastname: 'HARRY',
      },
      {
        idx: 7838,
        admissionnumber: 'EDVES/2023/001',
        firstname: 'Gbenga',
        lastname: 'Olatunji',
      },
      {
        idx: 7841,
        admissionnumber: 'ED/2023/003',
        firstname: 'Lawrence',
        lastname: 'Folorunso',
      },
      {
        idx: 7844,
        admissionnumber: 'TESTSTUDENT',
        firstname: 'Tope',
        lastname: 'Arogunyo Te',
      },
      {
        idx: 7847,
        admissionnumber: 'TS45325',
        firstname: 'John',
        lastname: 'Pambe',
      },
      {
        idx: 7850,
        admissionnumber: 'TEST3',
        firstname: 'Test3',
        lastname: 'TESTER',
      },
      {
        idx: 7853,
        admissionnumber: 'TEST2',
        firstname: 'Test2',
        lastname: 'TESTER',
      },
      {
        idx: 7856,
        admissionnumber: 'TEST1',
        firstname: 'Test1',
        lastname: 'TESTER',
      },
      {
        idx: 7859,
        admissionnumber: '2014',
        firstname: 'White',
        lastname: 'Joseph',
      },
      {
        idx: 7862,
        admissionnumber: '022',
        firstname: 'Abigail',
        lastname: 'Joel',
      },
      {
        idx: 7865,
        admissionnumber: '07019535546',
        firstname: 'Cletus',
        lastname: 'Okere',
      },
      {
        idx: 8694,
        admissionnumber: 'VIC124',
        firstname: 'Vic73',
        lastname: 'VIC',
      },
      {
        idx: 8697,
        admissionnumber: 'VIC125',
        firstname: 'Vic74',
        lastname: 'VIC',
      },
      {
        idx: 8700,
        admissionnumber: 'VIC126',
        firstname: 'Vic75',
        lastname: 'VIC',
      },
      {
        idx: 8736,
        admissionnumber: 'JIB35',
        firstname: 'Jibola35',
        lastname: 'JIB',
      },
      {
        idx: 8739,
        admissionnumber: 'JIB42',
        firstname: 'Jibola42',
        lastname: 'JIB',
      },
      {
        idx: 8742,
        admissionnumber: 'JIB40',
        firstname: 'Jibola40',
        lastname: 'JIB',
      },
      {
        idx: 8906,
        admissionnumber: '00435',
        firstname: 'James',
        lastname: 'Williams',
      },
    ],
    pagination_info: {
      total_students: 18,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Basic 2': {
    students: [
      {
        idx: 7868,
        admissionnumber: 'VIC121',
        firstname: 'Vic70',
        lastname: 'VIC',
      },
      {
        idx: 7871,
        admissionnumber: 'VIC120',
        firstname: 'Vic69',
        lastname: 'VIC',
      },
      {
        idx: 7874,
        admissionnumber: 'VIC119',
        firstname: 'Vic68',
        lastname: 'VIC',
      },
      {
        idx: 7877,
        admissionnumber: 'VIC118',
        firstname: 'Vic67',
        lastname: 'VIC',
      },
      {
        idx: 7880,
        admissionnumber: 'VIC117',
        firstname: 'Vic66',
        lastname: 'VIC',
      },
      {
        idx: 7883,
        admissionnumber: 'VIC116',
        firstname: 'Vic65',
        lastname: 'VIC',
      },
      {
        idx: 7886,
        admissionnumber: 'VIC115',
        firstname: 'Vic64',
        lastname: 'VIC',
      },
      {
        idx: 7889,
        admissionnumber: 'VIC114',
        firstname: 'Vic63',
        lastname: 'VIC',
      },
      {
        idx: 7892,
        admissionnumber: 'VIC113',
        firstname: 'Vic62',
        lastname: 'VIC',
      },
      {
        idx: 7895,
        admissionnumber: 'VIC112',
        firstname: 'Vic61',
        lastname: 'VIC',
      },
    ],
    pagination_info: {
      total_students: 10,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Basic 3': {
    students: [
      {
        idx: 8221,
        admissionnumber: '8080',
        firstname: 'Adams',
        lastname: 'Faseun',
      },
      {
        idx: 8221,
        admissionnumber: '8080',
        firstname: 'Bayo',
        lastname: 'ADEBAYO',
      },
      {
        idx: 8224,
        admissionnumber: 'KKPS/2014/537',
        firstname: 'GBENGA',
        lastname: 'OLATUNJI',
      },
      {
        idx: 8227,
        admissionnumber: '0801',
        firstname: 'Sunday',
        lastname: 'Falana',
      },
      {
        idx: 8230,
        admissionnumber: '141109',
        firstname: 'Akinfenwa',
        lastname: 'Akon',
      },
      {
        idx: 8233,
        admissionnumber: '1008/ABU/2019',
        firstname: 'John',
        lastname: 'abubakar',
      },
      {
        idx: 8236,
        admissionnumber: '1155',
        firstname: 'Peace',
        lastname: 'PETER',
      },
      {
        idx: 8239,
        admissionnumber: 'END/009',
        firstname: 'Penie',
        lastname: 'jey',
      },
      {
        idx: 8242,
        admissionnumber: 'DEMO1234',
        firstname: 'Praise',
        lastname: 'Arogunyo',
      },
      {
        idx: 8245,
        admissionnumber: 'IEC/0001',
        firstname: 'Bakiya',
        lastname: 'SULEIMAN',
      },
      {
        idx: 8248,
        admissionnumber: '123456789',
        firstname: 'Francis',
        lastname: 'Mbiriri',
      },
      {
        idx: 8248,
        admissionnumber: '123456789',
        firstname: 'Mark',
        lastname: 'wilson',
      },
      {
        idx: 8251,
        admissionnumber: 'EDVESSSSSSS',
        firstname: 'Temitope',
        lastname: 'AROGUNYO',
      },
      {
        idx: 8254,
        admissionnumber: 'P001',
        firstname: 'Abiodun',
        lastname: 'Famoye',
      },
      {
        idx: 8257,
        admissionnumber: 'SHE/2019/2020/04/010',
        firstname: 'Oke',
        lastname: 'FORTUNE',
      },
      {
        idx: 8260,
        admissionnumber: '001',
        firstname: 'OLUWANIFEMI',
        lastname: 'OVIOSUN',
      },
      {
        idx: 8263,
        admissionnumber: '5454',
        firstname: 'Tosin',
        lastname: 'Olajide ',
      },
      {
        idx: 8266,
        admissionnumber: 'A028',
        firstname: 'Abiodun',
        lastname: 'Famoye',
      },
      {
        idx: 8269,
        admissionnumber: 'DEMO/2021/001',
        firstname: 'Gbenga',
        lastname: 'Olatunji',
      },
      {
        idx: 8272,
        admissionnumber: 'TEE/2021/TOBI',
        firstname: 'Tobiloba',
        lastname: 'Ajayi',
      },
      {
        idx: 8275,
        admissionnumber: 'DEM/2021/002',
        firstname: 'Abiodun',
        lastname: 'Famoye',
      },
      {
        idx: 8275,
        admissionnumber: 'DEM/2021/002',
        firstname: 'Israel ',
        lastname: 'Okpeh',
      },
      {
        idx: 8278,
        admissionnumber: 'SRS001',
        firstname: 'Ifeanyi',
        lastname: 'Nwadiogbu',
      },
      {
        idx: 8281,
        admissionnumber: '0125',
        firstname: 'Timothy',
        lastname: 'Ihekoronye',
      },
      {
        idx: 8284,
        admissionnumber: '1123',
        firstname: 'Zainab',
        lastname: 'Zainab',
      },
      {
        idx: 8287,
        admissionnumber: '00613',
        firstname: 'Philip',
        lastname: 'Osatohanmwen',
      },
      {
        idx: 8290,
        admissionnumber: '999',
        firstname: 'Tallest',
        lastname: 'Tallest',
      },
      {
        idx: 8293,
        admissionnumber: 'EDVES/002',
        firstname: 'Arogunyo',
        lastname: 'temitope',
      },
      {
        idx: 8296,
        admissionnumber: '12345678900',
        firstname: 'Adeogo',
        lastname: 'Medubi',
      },
      {
        idx: 8299,
        admissionnumber: 'DEM/2021/167',
        firstname: 'Abiodun',
        lastname: 'Famoye',
      },
      {
        idx: 8302,
        admissionnumber: '0044',
        firstname: 'Ethan',
        lastname: 'Samuel',
      },
    ],
    pagination_info: {
      total_students: 31,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'BASIC 4': {
    students: [
      {
        idx: 6725,
        admissionnumber: 'A01',
        firstname: 'Yaya',
        lastname: 'OVIE',
      },
      {
        idx: 8305,
        admissionnumber: 'VIC25',
        firstname: 'Y',
        lastname: '',
      },
      {
        idx: 8308,
        admissionnumber: 'VIC21',
        firstname: 'U',
        lastname: '',
      },
    ],
    pagination_info: {
      total_students: 3,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'BASIC 6': {
    students: [
      {
        idx: 6402,
        admissionnumber: 'A23',
        firstname: 'Segun',
        lastname: 'Famoye',
      },
    ],
    pagination_info: {
      total_students: 1,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'BILLING CLASS': {
    students: [
      {
        idx: 7731,
        admissionnumber: 'VIC1',
        firstname: 'A',
        lastname: 'VIC ',
      },
      {
        idx: 7732,
        admissionnumber: 'VIC2',
        firstname: 'B',
        lastname: '',
      },
      {
        idx: 7733,
        admissionnumber: 'VIC3',
        firstname: 'C',
        lastname: '',
      },
      {
        idx: 7734,
        admissionnumber: 'VIC4',
        firstname: 'D',
        lastname: '',
      },
      {
        idx: 7735,
        admissionnumber: 'VIC5',
        firstname: 'E',
        lastname: '',
      },
      {
        idx: 7736,
        admissionnumber: 'VIC6',
        firstname: 'Eee',
        lastname: '',
      },
      {
        idx: 7737,
        admissionnumber: 'VIC7',
        firstname: 'G',
        lastname: '',
      },
      {
        idx: 7738,
        admissionnumber: 'VIC8',
        firstname: 'H',
        lastname: '',
      },
      {
        idx: 7739,
        admissionnumber: 'VIC9',
        firstname: 'I',
        lastname: '',
      },
      {
        idx: 7740,
        admissionnumber: 'VIC10',
        firstname: 'J',
        lastname: '',
      },
      {
        idx: 7741,
        admissionnumber: 'VIC11',
        firstname: 'K',
        lastname: '',
      },
      {
        idx: 7742,
        admissionnumber: 'VIC12',
        firstname: 'L',
        lastname: '',
      },
      {
        idx: 7743,
        admissionnumber: 'VIC13',
        firstname: 'M',
        lastname: '',
      },
      {
        idx: 7744,
        admissionnumber: 'VIC14',
        firstname: 'N',
        lastname: '',
      },
      {
        idx: 7745,
        admissionnumber: 'VIC15',
        firstname: 'O',
        lastname: '',
      },
      {
        idx: 7746,
        admissionnumber: 'VIC16',
        firstname: 'P',
        lastname: '',
      },
      {
        idx: 7747,
        admissionnumber: 'VIC17',
        firstname: 'Q',
        lastname: '',
      },
      {
        idx: 7748,
        admissionnumber: 'VIC18',
        firstname: 'R',
        lastname: '',
      },
      {
        idx: 7749,
        admissionnumber: 'VIC19',
        firstname: 'S',
        lastname: '',
      },
      {
        idx: 7750,
        admissionnumber: 'VIC20',
        firstname: 'T',
        lastname: '',
      },
    ],
    pagination_info: {
      total_students: 20,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'CRECHE C': {
    students: [
      {
        idx: 8380,
        admissionnumber: 'JIB13',
        firstname: 'Jibola13',
        lastname: 'JIB',
      },
    ],
    pagination_info: {
      total_students: 1,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  Eko: {
    students: [
      {
        idx: 7459,
        admissionnumber: '1223334444',
        firstname: 'Korede',
        lastname: 'Balogun',
      },
    ],
    pagination_info: {
      total_students: 1,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'FORMATIVE CLASS': {
    students: [
      {
        idx: 7897,
        admissionnumber: 'JIB11',
        firstname: 'Jibola11',
        lastname: 'JIB',
      },
      {
        idx: 7899,
        admissionnumber: '0088',
        firstname: 'Kehinde',
        lastname: 'Adepoju',
      },
      {
        idx: 7901,
        admissionnumber: '008',
        firstname: 'Justina',
        lastname: 'Edves',
      },
      {
        idx: 7903,
        admissionnumber: 'PLTCKS/019',
        firstname: 'Okonkwo',
        lastname: 'KENETH',
      },
      {
        idx: 7905,
        admissionnumber: 'PLTCKS/001',
        firstname: 'Ken',
        lastname: 'SARO-WIWA',
      },
      {
        idx: 7907,
        admissionnumber: 'JOE/2023/02',
        firstname: 'Seyi',
        lastname: 'Adeoti',
      },
      {
        idx: 7909,
        admissionnumber: 'JOE/2023/001',
        firstname: 'Tobi',
        lastname: 'Adams',
      },
      {
        idx: 7911,
        admissionnumber: '1997',
        firstname: 'Haastrup',
        lastname: 'Jim',
      },
      {
        idx: 7913,
        admissionnumber: 'DEMO/22/004',
        firstname: 'Robin',
        lastname: 'Jack',
      },
      {
        idx: 7915,
        admissionnumber: 'DEMO/22/003',
        firstname: 'Yusuf',
        lastname: 'Mohammed',
      },
      {
        idx: 7917,
        admissionnumber: '456',
        firstname: 'Goodness',
        lastname: 'Bola',
      },
      {
        idx: 7919,
        admissionnumber: '1234',
        firstname: 'Nansel',
        lastname: 'Mallan',
      },
      {
        idx: 7919,
        admissionnumber: '1234',
        firstname: 'Q',
        lastname: 'a',
      },
      {
        idx: 7921,
        admissionnumber: 'PLADEPEJU',
        firstname: 'Adepeju',
        lastname: 'Okoyomon',
      },
      {
        idx: 7923,
        admissionnumber: 'PLMOSES',
        firstname: 'Esele',
        lastname: 'Moses',
      },
      {
        idx: 7925,
        admissionnumber: '12345',
        firstname: 'Bukola',
        lastname: 'Jokotola',
      },
      {
        idx: 7925,
        admissionnumber: '12345',
        firstname: 'Charles',
        lastname: 'Falana',
      },
      {
        idx: 7927,
        admissionnumber: 'PLADEBOWALE',
        firstname: 'Faunmi',
        lastname: 'Adebowale',
      },
      {
        idx: 7929,
        admissionnumber: 'A00',
        firstname: 'Uju',
        lastname: 'Ujunwa',
      },
      {
        idx: 7931,
        admissionnumber: 'BITRUS',
        firstname: 'Kaduna',
        lastname: 'BITRUS',
      },
      {
        idx: 7933,
        admissionnumber: 'EDVES/SR/SW/001',
        firstname: 'Jomiloju',
        lastname: 'Olusanya',
      },
      {
        idx: 7935,
        admissionnumber: '77760',
        firstname: 'Abidemi',
        lastname: 'Taiwo',
      },
      {
        idx: 7937,
        admissionnumber: 'TSS/101',
        firstname: 'Testing',
        lastname: 'Child',
      },
      {
        idx: 7939,
        admissionnumber: '4040',
        firstname: 'Jane',
        lastname: 'ZOE',
      },
    ],
    pagination_info: {
      total_students: 24,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Grade 2': {
    students: [
      {
        idx: 8089,
        admissionnumber: 'EDVES/SDR/2023/005',
        firstname: 'Esther',
        lastname: 'Egbeolowo',
      },
      {
        idx: 8092,
        admissionnumber: 'EDVES/SDR/2023/004',
        firstname: 'Phebe',
        lastname: 'Folunrunso',
      },
      {
        idx: 8095,
        admissionnumber: 'EDVES/SDR/2023/003',
        firstname: 'Beauty',
        lastname: 'Odogwu',
      },
      {
        idx: 8098,
        admissionnumber: '25429',
        firstname: 'Kadmiel',
        lastname: 'Bitrus',
      },
      {
        idx: 8101,
        admissionnumber: '150901518',
        firstname: 'Emeka',
        lastname: 'Nwauzo',
      },
      {
        idx: 8104,
        admissionnumber: 'TESTBOARDER',
        firstname: 'Testb',
        lastname: 'TEST',
      },
      {
        idx: 8107,
        admissionnumber: 'ADEKEMI/2023/04',
        firstname: 'Oluwakemi',
        lastname: 'Adeoti',
      },
      {
        idx: 8110,
        admissionnumber: 'R123',
        firstname: 'Richard',
        lastname: 'Katongo',
      },
      {
        idx: 8113,
        admissionnumber: 'TYPE2',
        firstname: 'Blue',
        lastname: 'VIOLET',
      },
      {
        idx: 8116,
        admissionnumber: 'TYPE1',
        firstname: 'Red',
        lastname: 'VIOLET',
      },
      {
        idx: 8119,
        admissionnumber: 'ADETUTU/2023/01',
        firstname: 'Adetutu',
        lastname: 'Adeoti',
      },
      {
        idx: 8122,
        admissionnumber: '004',
        firstname: 'Justin',
        lastname: 'Olawale',
      },
      {
        idx: 8125,
        admissionnumber: 'EDVES/19/23',
        firstname: 'Cletus',
        lastname: 'Okere',
      },
      {
        idx: 8128,
        admissionnumber: '140408508',
        firstname: 'John',
        lastname: 'Adeshina',
      },
      {
        idx: 8131,
        admissionnumber: '2023-10',
        firstname: 'Sunday ',
        lastname: 'Jonathan ',
      },
      {
        idx: 8134,
        admissionnumber: '2023-08',
        firstname: 'Ikechukwu',
        lastname: 'Obi',
      },
      {
        idx: 8137,
        admissionnumber: '2023-06',
        firstname: 'Royalty ',
        lastname: 'Green',
      },
      {
        idx: 8140,
        admissionnumber: '2023-05',
        firstname: 'Joy',
        lastname: 'Monday ',
      },
      {
        idx: 8143,
        admissionnumber: '2023-04',
        firstname: 'Chioma ',
        lastname: 'Obi',
      },
      {
        idx: 8146,
        admissionnumber: '123',
        firstname: 'Abiodun',
        lastname: 'Folorunso',
      },
      {
        idx: 8146,
        admissionnumber: '123',
        firstname: 'Nenye',
        lastname: 'Joseph',
      },
    ],
    pagination_info: {
      total_students: 21,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Grade 3': {
    students: [
      {
        idx: 8149,
        admissionnumber: '2023-03',
        firstname: 'Genesis ',
        lastname: 'Green ',
      },
      {
        idx: 8152,
        admissionnumber: '2023-02',
        firstname: 'Ebuka ',
        lastname: 'Obi',
      },
      {
        idx: 8155,
        admissionnumber: '54321',
        firstname: 'Will',
        lastname: 'Anthony',
      },
      {
        idx: 8158,
        admissionnumber: '32321133',
        firstname: 'Yetunde',
        lastname: 'Edves',
      },
      {
        idx: 8161,
        admissionnumber: 'CAS23/001',
        firstname: 'Pauline',
        lastname: 'Paul',
      },
      {
        idx: 8164,
        admissionnumber: 'PLTCKS/018',
        firstname: 'Wike',
        lastname: 'NYESOM',
      },
      {
        idx: 8167,
        admissionnumber: 'PLTCKS/020',
        firstname: 'Ironsi',
        lastname: 'AGUYI',
      },
      {
        idx: 8170,
        admissionnumber: 'PLTCKS/017',
        firstname: 'Mohammed',
        lastname: 'MURTALA',
      },
      {
        idx: 8173,
        admissionnumber: 'PLTCKS/014',
        firstname: 'Kwakwanso',
        lastname: 'RABIU',
      },
      {
        idx: 8176,
        admissionnumber: 'PLTCKS/012',
        firstname: 'Bola',
        lastname: 'TINBU',
      },
      {
        idx: 8179,
        admissionnumber: 'PLTCKS/006',
        firstname: 'Abiola',
        lastname: 'MKO',
      },
      {
        idx: 8182,
        admissionnumber: 'PLTCKS/003',
        firstname: 'Yakubu',
        lastname: 'GOWON',
      },
      {
        idx: 8185,
        admissionnumber: 'PLTCKS/002',
        firstname: 'Muritala',
        lastname: 'GOWAN',
      },
      {
        idx: 8188,
        admissionnumber: '202219',
        firstname: 'Adrienne',
        lastname: 'Toluwanimi',
      },
      {
        idx: 8191,
        admissionnumber: 'NSO23/002',
        firstname: 'William',
        lastname: 'Sowho',
      },
      {
        idx: 8194,
        admissionnumber: '10000',
        firstname: 'Mercy',
        lastname: 'ULOMA',
      },
      {
        idx: 8197,
        admissionnumber: '1901',
        firstname: 'Gilbert',
        lastname: 'Pam',
      },
      {
        idx: 8200,
        admissionnumber: '1021',
        firstname: 'Paul',
        lastname: 'abiodun',
      },
    ],
    pagination_info: {
      total_students: 18,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Grade 4': {
    students: [
      {
        idx: 8391,
        admissionnumber: 'JIB8',
        firstname: 'Jibola8',
        lastname: 'JIB',
      },
      {
        idx: 8394,
        admissionnumber: 'JIB9',
        firstname: 'Jibola9',
        lastname: 'JIB',
      },
      {
        idx: 8397,
        admissionnumber: 'VIC31',
        firstname: 'Ccc',
        lastname: '',
      },
      {
        idx: 8400,
        admissionnumber: 'JIB1',
        firstname: 'Jibola1',
        lastname: 'JIB',
      },
      {
        idx: 8403,
        admissionnumber: 'JIB2',
        firstname: 'Jibola2',
        lastname: 'JIB',
      },
      {
        idx: 8406,
        admissionnumber: 'JIB3',
        firstname: 'Jibola3',
        lastname: 'JIB',
      },
      {
        idx: 8451,
        admissionnumber: 'JIB12',
        firstname: 'Jibola12',
        lastname: 'JIB',
      },
      {
        idx: 8454,
        admissionnumber: 'JIB10',
        firstname: 'Jibola10',
        lastname: 'JIB',
      },
      {
        idx: 8457,
        admissionnumber: 'VIC122',
        firstname: 'Vic71',
        lastname: 'VIC',
      },
      {
        idx: 8460,
        admissionnumber: 'VIC123',
        firstname: 'Vic72',
        lastname: 'VIC',
      },
      {
        idx: 8463,
        admissionnumber: 'VIC132',
        firstname: 'Vic81',
        lastname: 'VIC',
      },
      {
        idx: 8466,
        admissionnumber: 'VIC131',
        firstname: 'Vic80',
        lastname: 'VIC',
      },
      {
        idx: 8469,
        admissionnumber: 'VIC130',
        firstname: 'Vic79',
        lastname: 'VIC',
      },
    ],
    pagination_info: {
      total_students: 13,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Grade 5': {
    students: [
      {
        idx: 8409,
        admissionnumber: 'JIB38',
        firstname: 'Jibola38',
        lastname: 'JIB',
      },
      {
        idx: 8412,
        admissionnumber: 'JIB37',
        firstname: 'Jibola37',
        lastname: 'JIB',
      },
      {
        idx: 8415,
        admissionnumber: 'JIB36',
        firstname: 'Jibola36',
        lastname: 'JIB',
      },
      {
        idx: 8418,
        admissionnumber: 'JIB23',
        firstname: 'Jibola23',
        lastname: 'JIB',
      },
      {
        idx: 8421,
        admissionnumber: 'JIB24',
        firstname: 'Jibola24',
        lastname: 'JIB',
      },
      {
        idx: 8424,
        admissionnumber: 'JIB21',
        firstname: 'Jibola21',
        lastname: 'JIB',
      },
      {
        idx: 8427,
        admissionnumber: 'JIB22',
        firstname: 'Jibola22',
        lastname: 'JIB',
      },
      {
        idx: 8430,
        admissionnumber: 'JIB16',
        firstname: 'Jibola16',
        lastname: 'JIB',
      },
      {
        idx: 8433,
        admissionnumber: 'JIB44',
        firstname: 'Jibola44',
        lastname: 'JIB',
      },
      {
        idx: 8436,
        admissionnumber: 'JIB45',
        firstname: 'Jibola45',
        lastname: 'JIB',
      },
      {
        idx: 8439,
        admissionnumber: 'JIB43',
        firstname: 'Jibola43',
        lastname: 'JIB',
      },
      {
        idx: 8442,
        admissionnumber: 'JIB29',
        firstname: 'Jibola29',
        lastname: 'JIB',
      },
      {
        idx: 8445,
        admissionnumber: 'JIB30',
        firstname: 'Jibola30',
        lastname: 'JIB',
      },
      {
        idx: 8448,
        admissionnumber: 'JIB31',
        firstname: 'Jibola31',
        lastname: 'JIB',
      },
    ],
    pagination_info: {
      total_students: 14,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'JSS 1 A': {
    students: [
      {
        idx: 7942,
        admissionnumber: '234/JEFF/3R3',
        firstname: 'Jeff',
        lastname: 'Daramola',
      },
      {
        idx: 7945,
        admissionnumber: '246',
        firstname: 'Test',
        lastname: 'test',
      },
      {
        idx: 7948,
        admissionnumber: 'MR',
        firstname: 'Seth',
        lastname: 'Ayi-Bonte',
      },
      {
        idx: 7951,
        admissionnumber: '1234JAGA',
        firstname: 'Ahmed',
        lastname: 'Tinubu',
      },
      {
        idx: 7954,
        admissionnumber: '1234QUEEN',
        firstname: 'Queeneth',
        lastname: 'Idowu',
      },
      {
        idx: 7957,
        admissionnumber: 'SNS/008/321',
        firstname: 'Qatest',
        lastname: 'Student',
      },
      {
        idx: 7960,
        admissionnumber: 'DEMO/22/020',
        firstname: 'James',
        lastname: 'Ogunlowo ',
      },
    ],
    pagination_info: {
      total_students: 7,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Jss 1C': {
    students: [
      {
        idx: 8071,
        admissionnumber: 'VIC30',
        firstname: 'Bbb',
        lastname: '',
      },
      {
        idx: 8074,
        admissionnumber: 'VIC28',
        firstname: 'Yyy',
        lastname: '',
      },
      {
        idx: 8077,
        admissionnumber: 'VIC24',
        firstname: 'X',
        lastname: '',
      },
      {
        idx: 8080,
        admissionnumber: 'VIC23',
        firstname: 'W',
        lastname: '',
      },
      {
        idx: 8083,
        admissionnumber: 'VIC22',
        firstname: 'V',
        lastname: '',
      },
      {
        idx: 8086,
        admissionnumber: 'MIKE123',
        firstname: 'Michael',
        lastname: 'Ossai',
      },
      {
        idx: 8203,
        admissionnumber: 'JIB34',
        firstname: 'Jibola34',
        lastname: 'JIB',
      },
      {
        idx: 8206,
        admissionnumber: 'EDVES/19/24',
        firstname: 'Julius ',
        lastname: 'Pambe',
      },
      {
        idx: 8209,
        admissionnumber: '5645',
        firstname: 'Ada',
        lastname: 'Udoka',
      },
      {
        idx: 8212,
        admissionnumber: 'DEMO/2023/807/763038',
        firstname: 'Benjamin',
        lastname: 'Anangfio',
      },
      {
        idx: 8215,
        admissionnumber: '2023-09',
        firstname: 'Splendid ',
        lastname: 'Baridune',
      },
      {
        idx: 8218,
        admissionnumber: 'DEMO/2023/798/759442',
        firstname: 'Seth',
        lastname: 'Ayi-Bonte',
      },
    ],
    pagination_info: {
      total_students: 12,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'JSS 2 A': {
    students: [
      {
        idx: 8311,
        admissionnumber: 'TEST/F',
        firstname: 'Test',
        lastname: 'WILLIAMS',
      },
      {
        idx: 8314,
        admissionnumber: 'TEST/G',
        firstname: 'Test2',
        lastname: 'WILLIAMS',
      },
      {
        idx: 8317,
        admissionnumber: '2512',
        firstname: 'Temi',
        lastname: 'Olushola',
      },
      {
        idx: 8320,
        admissionnumber: '000234',
        firstname: 'Moyinoluwa',
        lastname: 'Aluko',
      },
      {
        idx: 8323,
        admissionnumber: '0003535',
        firstname: 'Moyinoluwa',
        lastname: 'Aluko',
      },
      {
        idx: 8326,
        admissionnumber: '22345',
        firstname: 'Philip',
        lastname: 'Akknlolu',
      },
      {
        idx: 8329,
        admissionnumber: 'TAHOMA',
        firstname: 'Tahoma',
        lastname: 'Nathaniel',
      },
      {
        idx: 8332,
        admissionnumber: 'CEPHAS',
        firstname: 'Cephas',
        lastname: 'Bogom',
      },
      {
        idx: 8335,
        admissionnumber: 'MALLUM',
        firstname: 'Blessing',
        lastname: 'Mallum',
      },
      {
        idx: 8338,
        admissionnumber: 'PLOLAWALE',
        firstname: 'Kolade',
        lastname: 'Olawale',
      },
      {
        idx: 8341,
        admissionnumber: 'PLNNAJI',
        firstname: 'Mrs',
        lastname: 'Nnaji',
      },
      {
        idx: 8344,
        admissionnumber: 'PLOSISANYA',
        firstname: 'Gbenga',
        lastname: 'Osisanya',
      },
      {
        idx: 8347,
        admissionnumber: 'PLAZAMAROGBE',
        firstname: 'Innocent',
        lastname: 'Azamarogbe',
      },
      {
        idx: 8350,
        admissionnumber: '080277',
        firstname: 'Jossy',
        lastname: 'eyo',
      },
      {
        idx: 8353,
        admissionnumber: 'GH001',
        firstname: 'Daniella',
        lastname: 'JOHN',
      },
      {
        idx: 8356,
        admissionnumber: 'DEMO/KENT/2023008',
        firstname: 'Kent',
        lastname: 'Jude',
      },
      {
        idx: 8359,
        admissionnumber: '1234AJAYI',
        firstname: 'George',
        lastname: 'Ajayi',
      },
      {
        idx: 8362,
        admissionnumber: 'DEMO/22/014',
        firstname: 'Orimen',
        lastname: 'James',
      },
      {
        idx: 8365,
        admissionnumber: '201',
        firstname: 'It',
        lastname: '',
      },
      {
        idx: 8365,
        admissionnumber: '201',
        firstname: 'Segun',
        lastname: 'Edves',
      },
    ],
    pagination_info: {
      total_students: 20,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'Jss 2B': {
    students: [
      {
        idx: 8371,
        admissionnumber: 'JIB14',
        firstname: 'Jibola14',
        lastname: 'JIB',
      },
      {
        idx: 8374,
        admissionnumber: 'ADEKEMI/2023/03',
        firstname: 'Seunfunmi',
        lastname: 'Adeoti',
      },
      {
        idx: 8377,
        admissionnumber: '00022',
        firstname: 'Seth',
        lastname: 'Ayi-Bonte',
      },
    ],
    pagination_info: {
      total_students: 3,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  "Pelumi\\'s class": {
    students: [
      {
        idx: 6394,
        admissionnumber: '1111',
        firstname: 'Pelumi',
        lastname: 'Pelumi',
      },
    ],
    pagination_info: {
      total_students: 1,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'primary 3': {
    students: [
      {
        idx: 7800,
        admissionnumber: 'KAY/20210401/JOHN',
        firstname: 'John',
        lastname: 'Adeoni',
      },
    ],
    pagination_info: {
      total_students: 1,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'SDR CLASS 2023': {
    students: [
      {
        idx: 7788,
        admissionnumber: 'VIC128',
        firstname: 'Vic77',
        lastname: 'VIC',
      },
      {
        idx: 7789,
        admissionnumber: 'TESTDAY',
        firstname: 'Test',
        lastname: 'TEST',
      },
      {
        idx: 7790,
        admissionnumber: '005',
        firstname: 'Esther ',
        lastname: 'Egbeolowo ',
      },
      {
        idx: 7790,
        admissionnumber: '005',
        firstname: 'Johnson',
        lastname: 'Akintunde',
      },
      {
        idx: 7791,
        admissionnumber: 'JIB41',
        firstname: 'Jibola41',
        lastname: 'JIB',
      },
      {
        idx: 7792,
        admissionnumber: 'INI/001',
        firstname: 'Chioma',
        lastname: 'Iyanu',
      },
      {
        idx: 7793,
        admissionnumber: '6666',
        firstname: 'Oluwashikemi',
        lastname: 'Oladele',
      },
      {
        idx: 7794,
        admissionnumber: '9999',
        firstname: 'Festus',
        lastname: 'Adeyemo',
      },
      {
        idx: 7795,
        admissionnumber: '20115',
        firstname: 'Julius',
        lastname: 'John',
      },
      {
        idx: 7796,
        admissionnumber: '3522',
        firstname: 'Adaolisa',
        lastname: 'Okafor',
      },
    ],
    pagination_info: {
      total_students: 10,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'TEST CLASS': {
    students: [
      {
        idx: 7801,
        admissionnumber: 'TEST/A',
        firstname: 'Peace',
        lastname: 'PETERS',
      },
      {
        idx: 7802,
        admissionnumber: 'TEST/B',
        firstname: 'Ugo',
        lastname: 'KAINE',
      },
    ],
    pagination_info: {
      total_students: 2,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
  'YEAR 7': {
    students: [
      {
        idx: 7805,
        admissionnumber: 'KING003',
        firstname: 'King',
        lastname: 'DAVID',
      },
    ],
    pagination_info: {
      total_students: 1,
      page: 1,
      total_pages: 1,
      next_page: null,
      prev_page: null,
    },
  },
};
